### PR TITLE
New option extra columns

### PR DESCRIPTION
**Pull request by FrederikHeber**
Hey Tobias,

first of all: Thanks! I was looking high and low for a small terminal program to convert arbitrary CSV files into sqlite databases, and your termsql save me a lot of hassle and time.

I've added two options of my own: 
1. "--append" does not drop a present table. Hence, multiple files can be read and added to the same table if the data is split up into multiple but "column-consistent" files, i.e. they share the same structure.
2. "extra-columns" allows to specify further (named) columns that are given a fixed value per parsed file. This is also useful in the context of placing several CSV files into the same table. If values in these files differ because a different parameter was used, that is not present as a column in the CSV content itself, then it can still be added manually using this option.

I'm not too familar with Python, so if you have any comments on the code quality or want me to change stuff, don't hesitate. 
Also, do you have some kind of testsuite or do you know how to do such a thing within the python "setup.py" scheme. I know C++ a lot better and there I use autotools/autotest or cmake/ctest. I found "pytest" by googling, any experience on that? For my own sake, I probably will start one in the future and would like to give more pull-requests :)

Kind regards,

Frederik

### CODE REVIEW

**Comment by tobimensch** [comment]
Hello Frederik,

thanks for your patches.

I merged your commit  36c7e26 with small changes.

I DID NOT merge your commit be385dd however, because I'm not quite sure it is solving the problem in the right way or that termsql should be solving this kind of problem in the first place.

Please note that I'm not completely against it, I'm just not eager to add it in this form (yet) as it does look like a corner case. I would like a real life usage example that illustrates why it would be a good idea to have this.

**Comment by tobimensch** [comment]
> I'm not too familar with Python, so if you have any comments on the code quality or want me to change stuff, don't hesitate. 
> Also, do you have some kind of testsuite or do you know how to do such a thing within the python "setup.py" scheme. I know C++ a lot better and there I use autotools/autotest or cmake/ctest. I found "pytest" by googling, any experience on that? For my own sake, I probably will start one in the future and would like to give more pull-requests :)

I'm not really familiar with python test suites either. I agree that it would be a great idea to add tests to the repository, pull requests in that direction are more than welcome.

**Comment by FrederikHeber** [comment]
Just to add my use case:
I'm an applied mathematician working in the field of material science. One of my codes chunks out tab-separated data files per run such as

level shortrange_energy longrange_energy
1 0.1 2.7e+2
...

The results in the file depend on a set of parameters controlling the calculations' precision. These are not contained in above file as it would otherwise become unreadable to humans.

I want all the data to end up in an SQL database to allow easy extraction of subsets of the data for easy plotting with the latex package [pgfplots](https://sourceforge.net/projects/pgfplots). To this end, I use "extra-columns" to add these parameters to the parsed tab-separated files and place them all in the same table. For the last step, I need "append". Afterwards SQL's SELECT statement allows easy extraction, e.g. 

`SELECT longrange_energy FROM energies WHERE level=1 and mesh=7`,

where mesh is some "hidden" parameter.

**Comment by FrederikHeber** [comment]
And the testsuite stuff: I'll have a look at pytest and how to add it to the project. But probably not right away :)

**Comment by tobimensch** [comment]
couldn't you do something like this instead?

cat data | ./termsql -o db.db --append "ALTER TABLE tbl ADD COLUMN foo TEXT DEFAULT 'bar'; ALTER TABLE tbl ADD COLUMN bar TEXT DEFAULT 'foo';"

**Comment by FrederikHeber** [comment]
As a matter of fact, yes! I was not aware that I could simply add some 
arbitrary SQL commands to the termsql command line ...

Then, indeed, the commit is pointless. Thanks for the pointer!

**Comment by tobimensch** [comment]
> As a matter of fact, yes! I was not aware that I could simply add some
> arbitrary SQL commands to the termsql command line ...

That's basically the whole point of termsql. :-) You can also put these commands into a query file with the -q --queryfile option.

**Pull request merged**
